********************************Задание № 1 (Numpy)***************************************

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 6], [2, 8,], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

********************************Задание № 2 (Numpy)***************************************

In [7]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [13]:
a_centered.shape

(5, 2)

********************************Задание № 3 (Numpy)***************************************

In [31]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [32]:
a_centered_sp = a_centered_sp/(a_centered.shape[0]-1)
a_centered_sp

2.0

********************************Задание № 4 (Numpy)***************************************

In [34]:
b = np.cov(a.T)
b

array([[1. , 2. ],
       [2. , 4.3]])

********************************Задание № 1 (Pandas)***************************************

In [ ]:
import pandas as pd

In [4]:
authors = pd.DataFrame({'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']})

In [5]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [6]:
books = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3], 'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price': [450, 300, 350, 500, 450, 370, 290]})

In [7]:
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

********************************Задание № 2 (Pandas)***************************************

In [66]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

********************************Задание № 3 (Pandas)***************************************

In [23]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

********************************Задание № 4 (Pandas)***************************************

In [79]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [81]:
authors_stat = pd.DataFrame({'min_price' : authors_price.groupby('author_name')['price'].min(),
                             'max_price' : authors_price.groupby('author_name')['price'].max(),
                             'mean_price' : authors_price.groupby('author_name')['price'].mean()})
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000